home/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns

from .views import *


urlpatterns = [

	url(r'^log-out/$', log_out, name='log-out'),
	url(r'^sign-in/$', sign_in, name='sign_in'),
	# url(r'^d/change-password/$', change_password, name='change-password'),
	url(r'^$', dashboard, name='dashboard'),
	url(r'^work-page-search/a/$', work_page_search, name='work-page-search'),
	url(r'^employee-search-works/a/$', employee_search, name='employee-search-works'),
	url(r'^general-all-user/(?P<u_slug>[\w-]+)/$', general_all_user, name='general-all-user'),
	url(r'^employee-page/(?P<e_id>[\w-]+)/$', employee_page, name='employee_page'),
	url(r'^employee-page-search/(?P<e_id>[\w-]+)/$', employee_page_search, name='employee-page-search'),
	url(r'^customer-page/(?P<c_id>[\w-]+)/$', customer_page, name='customer-page'),
	url(r'^edit-user/(?P<user_type>[\w-]+)/(?P<user_id>[\w-]+)/$', edit_user, name='edit-user'),
	url(r'^employee-location/(?P<e_id>[\w-]+)/(?P<day>[0-9]{2})-(?P<month>[0-9]{2})-(?P<year>[0-9]{4})/$', employee_day_checks, name='employee-day-checks'),
	url(r'^employee-add-to-customer/$', employee_add_to_customer, name='employee-add-to-customer'),
	url(r'^my-works-list/c/$', customer_works_list, name='customer-works-list'),
	url(r'^sign-up/$', sign_up, name='sign-up'),

]

workchecker/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.utils import translation
from django.views import generic
from django.views.static import serve
from home.views import *
from django.views import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^administration/', admin.site.urls,name="admin"),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
        url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media')
]

urlpatterns += [
    url(r'^', include("home.urls", namespace="home")),
]

urlpatterns += staticfiles_urlpatterns()




@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)


if settings.DEBUG is False:   #if DEBUG is True it will be served automatically
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT }, name='static'),
        url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media')
    ]
urlpatterns += staticfiles_urlpatterns()

home/models.py
from django.db import models

# Create your models here.

home/forms.py
import os

from django import forms
from django.utils.translation import ugettext as _

import pyrebase
from django.conf import settings

firebase = pyrebase.initialize_app(settings.FB_CONFIG)
auth_fb = firebase.auth()
database_fb = firebase.database()

user_type_choice = (
    (1,'Admin'),
    (2,'Customer'),
    (3,'Employee'),
)

class LoginForm(forms.Form):
    username_or_email = forms.EmailField(max_length=255,min_length=2,required=True,widget=forms.EmailInput(attrs={'placeholder':_('Email'),'autocomplete':'off','class': 'form-control form-control-solid placeholder-no-fix',}))
    password = forms.CharField(max_length=255,required=True,widget=forms.PasswordInput(attrs={'placeholder':_('Password'),'autocomplete':'off','class': 'form-control form-control-solid placeholder-no-fix',}))
    remember_me = forms.BooleanField(required=False)

class SignupForm(forms.Form):
    first_name = forms.CharField(max_length=255,min_length=2,required=True,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    last_name = forms.CharField(max_length=255,min_length=2,required=True,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    email = forms.EmailField(max_length=255,min_length=2,required=True,widget=forms.EmailInput(attrs={'autocomplete':'off','class': 'form-control',}))
    password = forms.CharField(max_length=255,required=True,widget=forms.PasswordInput(attrs={'autocomplete':'off','class': 'form-control',}))
    code = forms.CharField(max_length=255,min_length=2,required=False,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    address = forms.CharField(max_length=255,min_length=2,required=False,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    post_code = forms.CharField(max_length=255,min_length=2,required=False,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    city = forms.CharField(max_length=255,min_length=2,required=False,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    phone = forms.CharField(max_length=255,min_length=2,required=False,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    image = forms.ImageField(required=False)
    document = forms.FileField(required=False)
    address_document = forms.FileField(required=False)
    contract_file = forms.FileField(required=False)
    user_type = forms.ChoiceField(required=True,choices=user_type_choice,widget=forms.Select(attrs={'autocomplete':'off','class': 'form-control',}))


class UserEditForm(forms.Form):
    first_name = forms.CharField(max_length=255,min_length=2,required=True,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    last_name = forms.CharField(max_length=255,min_length=2,required=True,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    code = forms.CharField(max_length=255,min_length=2,required=True,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    address = forms.CharField(max_length=255,min_length=2,required=False,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    post_code = forms.CharField(max_length=255,min_length=2,required=False,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    city = forms.CharField(max_length=255,min_length=2,required=False,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    phone = forms.CharField(max_length=255,min_length=2,required=False,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control',}))
    image = forms.ImageField(required=False)
    document = forms.FileField(required=False)
    address_document = forms.FileField(required=False)
    contract_file = forms.FileField(required=False)
    user_type = forms.ChoiceField(required=True,choices=user_type_choice,widget=forms.Select(attrs={'autocomplete':'off','class': 'form-control',}))

class CustomerEmployeeForm(forms.Form):
    customer = forms.ChoiceField(required=True,choices=[],widget=forms.Select(attrs={'autocomplete':'off','class': 'form-control select2',}))
    employees = forms.MultipleChoiceField(required=True,choices=[],widget=forms.SelectMultiple(attrs={'autocomplete':'off','class': 'form-control select2-multiple'}))
    start_date = forms.DateTimeField(required=True,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control','size':10,'readonly':'',}))
    end_date = forms.DateTimeField(required=True,widget=forms.TextInput(attrs={'autocomplete':'off','class': 'form-control','size':16,'readonly':'',}))
    def __init__(self,*args, **kwargs):
        super(CustomerEmployeeForm, self).__init__(*args, **kwargs)
        all_users = database_fb.child("users").get()
        all_customers_list = []
        all_employees_list = []
        for all_users_item in all_users.each():
            print(all_users_item.val()['user_type'])
            if int(all_users_item.val()['user_type']) == 2:
                all_customers_list.append([all_users_item.key(),"{} {}".format(all_users_item.val()['first_name'],all_users_item.val()['last_name'])])
            elif int(all_users_item.val()['user_type']) == 3:
                all_employees_list.append([all_users_item.key(),"{} {}".format(all_users_item.val()['first_name'],all_users_item.val()['last_name'])])
            else:
                pass
                # print("all_users_item.val() = {} ".format(all_users_item.val()))
        # customer_obj = customer_obj
        # print("all_employees_list = {}".format(all_employees_list))
        # employees_obj = customer_obj
        self.fields['customer'].choices = all_customers_list
        self.fields['employees'].choices = all_employees_list

class EmployeePageWorkSearchForm(forms.Form):
    start_date = forms.CharField(required=False,widget=forms.DateInput(attrs={'autocomplete':'off','class': 'form-control ','placeholder':'From'}))
    end_date = forms.CharField(required=False,widget=forms.DateInput(attrs={'autocomplete':'off','class': 'form-control','placeholder':'To',}))
    def __init__(self,*args, **kwargs):
        super(EmployeePageWorkSearchForm, self).__init__(*args, **kwargs)


class EmployeeWorkSearchForm(forms.Form):
    employee = forms.ChoiceField(required=True,choices=[],widget=forms.Select(attrs={'autocomplete':'off','class': 'form-control select2','placeholder':'Employee'}))
    start_date = forms.CharField(required=False,widget=forms.DateInput(attrs={'autocomplete':'off','class': 'form-control ','placeholder':'From'}))
    end_date = forms.CharField(required=False,widget=forms.DateInput(attrs={'autocomplete':'off','class': 'form-control','placeholder':'To',}))
    def __init__(self,user_type,user_id,*args, **kwargs):
        super(EmployeeWorkSearchForm, self).__init__(*args, **kwargs)
        all_users = database_fb.child("users").get()
        all_employees_list = []
        customer_employees_list = []

        if int(user_type) == 2:
            try:
                customer_employee_dates = database_fb.child("customer_employee").child(user_id).get()
                all_data_list = dict(customer_employee_dates.val())
                for all_data_list_item in all_data_list.items():
                    # print(all_data_list_item[0])
                    # print(all_data_list_item[1])
                    for all_data_list_item_x in dict(all_data_list_item[1]).items():
                        # print('#############################################################################')
                        if all_data_list_item_x[0] not in customer_employees_list:
                            customer_employees_list.append(all_data_list_item_x[0])
                        # print(all_data_list_item_x)
                        # print('*****************************************************************************')
            except:
                pass
        # print("customer_employees_list={}".format(customer_employees_list))
        try:
            for all_users_item in all_users.each():
                print(all_users_item.val()['user_type'])
                if int(all_users_item.val()['user_type']) == 3:
                    if int(user_type) == 2:
                        if all_users_item.key() in customer_employees_list:
                            all_employees_list.append([all_users_item.key(),"{} {}".format(all_users_item.val()['first_name'],all_users_item.val()['last_name'])])
                    elif int(user_type) == 1:
                        all_employees_list.append([all_users_item.key(),"{} {}".format(all_users_item.val()['first_name'],all_users_item.val()['last_name'])])

                else:
                    pass
                    # print("all_users_item.val() = {} ".format(all_users_item.val()))
        except:
            pass
        # customer_obj = customer_obj
        # print("all_employees_list = {}".format(all_employees_list))
        # employees_obj = customer_obj
        self.fields['employee'].choices = all_employees_list



class WorkSearchForm(forms.Form):
    customer = forms.ChoiceField(required=False,choices=[],widget=forms.Select(attrs={'autocomplete':'off','class': 'form-control select2','placeholder':'Customer',}))
    date = forms.CharField(required=False,widget=forms.DateInput(attrs={'autocomplete':'off','class': 'form-control ','placeholder':'Date'}))
    def __init__(self,*args, **kwargs):
        super(WorkSearchForm, self).__init__(*args, **kwargs)
        all_users = database_fb.child("users").get().each()
        all_customers_list = []
        # all_employees_list = []
        for all_users_item in all_users:
            print(all_users_item.val()['user_type'])
            if int(all_users_item.val()['user_type']) == 2:
                all_customers_list.append([all_users_item.key(),"{} {}".format(all_users_item.val()['first_name'],all_users_item.val()['last_name'])])

templates/home/admin/customer-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html{% extends 'main_base.html' %}
{% load static %}
{% block title_container %}

{% endblock %}


{% block head_container %}
{% endblock %}
{% block head_under_container %}

        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <link href="{% static 'main/assets/global/plugins/datatables/datatables.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'main/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css' %}" rel="stylesheet" type="text/css" />
        <!-- END PAGE LEVEL PLUGINS -->

{% endblock %}


{% block content_container %}

            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <!-- BEGIN CONTENT BODY -->
                <div class="page-content">
                    <!-- BEGIN PAGE HEAD-->
                    <div class="page-head">
                        <!-- BEGIN PAGE TITLE -->
                        <div class="page-title">
                            <h1>Customers
{#                                <small>responsive extension demos</small>#}
                            </h1>
                        </div>
                        <!-- END PAGE TITLE -->
                    </div>
                    <!-- END PAGE HEAD-->
                    <!-- BEGIN PAGE BREADCRUMB -->
                    <ul class="page-breadcrumb breadcrumb">
                        <li>
                            <a href="{% url 'home:dashboard' %}">Dashboard</a>
                            <i class="fa fa-circle"></i>
                        </li>
                        <li>
                            <span class="active">Customers</span>
                        </li>
                    </ul>
                    <!-- END PAGE BREADCRUMB -->

                    <div class="row">
                        <div class="col-md-12">
                            <!-- BEGIN EXAMPLE TABLE PORTLET-->
                            <div class="portlet box red">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-globe"></i>Customers List</div>
                                    <div class="tools"> </div>
                                </div>
                                <div class="portlet-body">
                                    <table class="table table-striped table-bordered table-hover dt-responsive" width="100%" id="sample_4">
                                        <thead>
                                            <tr>
                                                <th class="all">n</th>
                                                <th class="all">Photo</th>
                                                <th class="all">First name</th>
                                                <th class="min-phone-l">Last name</th>
                                                <th class="min-tablet">Phone</th>
                                                <th class="min-tablet">Status</th>
                                                <th class="min-tablet">/</th>
{#                                                <th class="none">User Type</th>#}
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for all_data_list_item in all_data_list %}
                                                <tr>
                                                    <td>{{ forloop.counter }}</td>
                                                    <td><img height="50" src="{% if all_data_list_item.image %}{{ all_data_list_item.image }}{% else %}{% endif %}"></td>
                                                    <td>{{ all_data_list_item.first_name }}</td>
                                                    <td>{{ all_data_list_item.last_name }}</td>
                                                    <td>{{ all_data_list_item.phone }}</td>
                                                    <td>{{ all_data_list_item.status }}</td>
                                                    <td>
                                                        <a href="{% url 'home:customer-page' all_data_list_item.id %}" class="btn dark btn-sm btn-outline sbold uppercase">
                                                            <i class="fa fa-eye"></i> View </a> |
                                                        <a href="{% url 'home:edit-user' 'customer' all_data_list_item.id %}" class="btn btn-outline btn-circle btn-sm purple">
                                                            <i class="fa fa-edit"></i> Edit </a>
                                                    </td>
{#                                                    <td>#}
{#                                                        {{  }}#}
{#                                                    </td>#}
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <!-- END EXAMPLE TABLE PORTLET-->
                        </div>
                    </div>
                    <!-- END PAGE BASE CONTENT -->
                </div>
                <!-- END CONTENT BODY -->
            </div>
            <!-- END CONTENT -->

{% endblock %}


{% block js_block %}


        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="{% static 'main/assets/global/scripts/datatable.js' %}" type="text/javascript"></script>
        <script src="{% static 'main/assets/global/plugins/datatables/datatables.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'main/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js' %}" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL SCRIPTS -->
        <script src="{% static 'main/assets/global/scripts/app.min.js' %}" type="text/javascript"></script>
        <!-- END THEME GLOBAL SCRIPTS -->
        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        <script src="{% static 'main/assets/pages/scripts/table-datatables-responsive.min.js' %}" type="text/javascript"></script>
        <!-- END PAGE LEVEL SCRIPTS -->

{% endblock %}

>

templates/home/admin/employee-add-to-customer.html
{% extends 'main_base.html' %}
{% load static %}
{% block title_container %}

{% endblock %}


{% block head_container %}


{% endblock %}


{% block head_under_container %}

        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <link href="{% static 'main/assets/global/plugins/select2/css/select2.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'main/assets/global/plugins/select2/css/select2-bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <link href="{% static 'main/assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'main/assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'main/assets/global/plugins/bootstrap-timepicker/css/bootstrap-timepicker.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'main/assets/global/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'main/assets/global/plugins/clockface/css/clockface.css' %}" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.6.5/sweetalert2.min.css"
          type="text/css"/>
{% endblock %}


{% block content_container %}


            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <!-- BEGIN CONTENT BODY -->
                <div class="page-content">
                    <!-- BEGIN PAGE BREADCRUMB -->
                    <ul class="page-breadcrumb breadcrumb">
                        <li>
                            <a href="{% url 'home:dashboard' %}">Dashboard</a>
                            <i class="fa fa-circle"></i>
                        </li>
                        <li>
                            <span class="active">Employess add to Customer</span>
                        </li>
                    </ul>
                    <!-- END PAGE BREADCRUMB -->
                    <!-- BEGIN PAGE BASE CONTENT -->
                    <div class="row">
                        <div class="col-md-12 ">
                            <!-- BEGIN SAMPLE FORM PORTLET-->
                            <div class="portlet light bordered">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="icon-settings font-dark"></i>
                                        <span class="caption-subject font-dark sbold uppercase">Employess add to Customer</span>
                                    </div>
                                </div>
                                <div class="portlet-body form">
                                    <form class="form-horizontal" role="form" action="" method="post">
                                        {% csrf_token %}
                                        <div class="form-body">
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Customer</label>
                                                <div class="col-md-9">
                                                    {{ customer_employee_form.customer }}
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Employees</label>
                                                <div class="col-md-9">
                                                    {{ customer_employee_form.employees }}
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-lg-3 col-md-3 col-sm-3 control-label">Start Date</label>
                                                <div class="col-lg-6 col-md-7 col-sm-8">
                                                    <div class="input-group date form_datetime bs-datetime" data-date="{{ now.year }}-01-16T05:25:07Z" data-date-format="Y-MM-D HH:mm:ss">
                                                        {{ customer_employee_form.start_date }}
{#                                                        <input class="form-control" size="16" type="text" value="" readonly>#}
                                                        <span class="input-group-addon">
                                                            <button class="btn default date-reset" type="button">
                                                                <i class="fa fa-times"></i>
                                                            </button>
                                                        </span>
                                                        <span class="input-group-addon">
                                                            <button class="btn default date-set" type="button">
                                                                <i class="fa fa-calendar"></i>
                                                            </button>
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-lg-3 col-md-3 col-sm-3 control-label">End Date</label>
                                                <div class="col-lg-6 col-md-7 col-sm-8">
                                                    <div class="input-group date form_datetime bs-datetime" data-date="{{ now.year }}-01-16T05:25:07Z" data-date-format="Y-MM-D HH:mm:ss">
                                                        {{ customer_employee_form.end_date }}
{#                                                        <input class="form-control" size="16" type="text" value="" readonly>#}
                                                        <span class="input-group-addon">
                                                            <button class="btn default date-reset" type="button">
                                                                <i class="fa fa-times"></i>
                                                            </button>
                                                        </span>
                                                        <span class="input-group-addon">
                                                            <button class="btn default date-set" type="button">
                                                                <i class="fa fa-calendar"></i>
                                                            </button>
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-actions">
                                            <div class="row">
                                                <div class="col-md-offset-3 col-md-9">
                                                    <button type="submit" class="btn green">Submit</button>
                                                    <button type="button" class="btn default">Cancel</button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- END CONTENT BODY -->
            </div>
            <!-- END CONTENT -->

{% endblock %}


{% block js_block %}

        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="{% static 'main/assets/global/plugins/select2/js/select2.full.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'main/assets/pages/scripts/components-select2.min.js' %}" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->
        <script src="{% static 'main/assets/global/plugins/moment.min.js' %}" type="text/javascript"></script>
{#        <script src="{% static 'main/assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.js' %}" type="text/javascript"></script>#}
{#        <script src="{% static 'main/assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}" type="text/javascript"></script>#}
{#        <script src="{% static 'main/assets/global/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js' %}" type="text/javascript"></script>#}
        <script src="{% static 'main/assets/global/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js' %}" type="text/javascript"></script>
{#        <script src="{% static 'main/assets/global/plugins/clockface/js/clockface.js' %}" type="text/javascript"></script>#}
{#        <script src="{% static 'main/assets/pages/scripts/components-date-time-pickers.min.js' %}" type="text/javascript"></script>#}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.6.5/sweetalert2.min.js"></script>
        <script>
            dateTimeOptions = {
            'format': 'yyyy-mm-dd hh:ii',
            'autoclose': false,
            'showMeridian' : true
            };
            $('#id_start_date').datetimepicker(dateTimeOptions);
            $('#id_end_date').datetimepicker(dateTimeOptions);
            {#widgets = {#}
            {#    #NOT Use localization and set a default format#}
            {#    'datetime': DateTimeWidget(options = dateTimeOptions)#}
{#    }#}
    </script>
    {% if success_message %}
        <script>

            $(document).ready(function () {
                swal(
                    '{{ success_message }}',
                    '',
                    'success'
                );
            });

        </script>
    {% endif %}
{% endblock %}

templates/home/admin/employee-list.html
{% extends 'main_base.html' %}

{% block title_container %}

{% endblock %}

{% block head_container %}

{% endblock %}


{% block content_container %}



{% endblock %}


{% block js_block %}

{% endblock %}

templates/home/admin/user-add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>